---
name: Security Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Gitleaks secrets scannign
  gitleaks:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/gitleaks.yml
    with:
      fail_on_findings: false
      enable_pr_comments: true
      # config_path: '.github/security/gitleaks.yml' # optional, can be omitted if using default config
    secrets: inherit
  
  semgrep:
    permissions:
      contents: read
      security-events: write
      actions: read
    needs: gitleaks
    uses: ./.github/workflows/semgrep.yml
    secrets: inherit
    with:
      scan_level: WARNING